openapi: 3.2.0
info:
  title: GZW Data Provisions API
  version: 4.0.0
  description: Comprehensive Gray Zone Warfare game data API.
servers:
- url: https://gzw-data.dev
tags:
- name: Provisions
paths:
  /api/provisions:
    get:
      summary: provisions (37 items)
      tags:
      - Provisions
  /api/provisions/{id}:
    get:
      summary: Get one provisions record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Provisions
  /api/v1/provisions:
    get:
      summary: provisions (37 items)
      tags:
      - Provisions
  /api/v1/provisions/{id}:
    get:
      summary: Get one provisions record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Provisions
