openapi: 3.2.0
info:
  title: GZW Data Lockboxes API
  version: 4.0.0
  description: Comprehensive Gray Zone Warfare game data API.
servers:
- url: https://gzw-data.dev
tags:
- name: Lockboxes
paths:
  /api/lockboxes:
    get:
      summary: lockboxes (3 items)
      tags:
      - Lockboxes
  /api/lockboxes/{id}:
    get:
      summary: Get one lockboxes record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Lockboxes
  /api/v1/lockboxes:
    get:
      summary: lockboxes (3 items)
      tags:
      - Lockboxes
  /api/v1/lockboxes/{id}:
    get:
      summary: Get one lockboxes record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Lockboxes
