openapi: 3.2.0
info:
  title: GZW Data Repair Kits API
  version: 4.0.0
  description: Comprehensive Gray Zone Warfare game data API.
servers:
- url: https://gzw-data.dev
tags:
- name: Repair Kits
paths:
  /api/repair_kits:
    get:
      summary: repair_kits (6 items)
      tags:
      - Repair Kits
  /api/repair_kits/{id}:
    get:
      summary: Get one repair_kits record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Repair Kits
  /api/v1/repair_kits:
    get:
      summary: repair_kits (6 items)
      tags:
      - Repair Kits
  /api/v1/repair_kits/{id}:
    get:
      summary: Get one repair_kits record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Repair Kits
