openapi: 3.2.0
info:
  title: GZW Data Charging Handle API
  version: 4.0.0
  description: Comprehensive Gray Zone Warfare game data API.
servers:
- url: https://gzw-data.dev
tags:
- name: Charging Handle
paths:
  /api/charging_handle:
    get:
      summary: charging_handle (11 items)
      tags:
      - Charging Handle
  /api/charging_handle/{id}:
    get:
      summary: Get one charging_handle record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Charging Handle
  /api/v1/charging_handle:
    get:
      summary: charging_handle (11 items)
      tags:
      - Charging Handle
  /api/v1/charging_handle/{id}:
    get:
      summary: Get one charging_handle record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Charging Handle
