openapi: 3.2.0
info:
  title: GZW Data Loot Items API
  version: 4.0.0
  description: Comprehensive Gray Zone Warfare game data API.
servers:
- url: https://gzw-data.dev
tags:
- name: Loot Items
paths:
  /api/loot_items:
    get:
      summary: loot_items (120 items)
      tags:
      - Loot Items
  /api/loot_items/{id}:
    get:
      summary: Get one loot_items record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Loot Items
  /api/v1/loot_items:
    get:
      summary: loot_items (120 items)
      tags:
      - Loot Items
  /api/v1/loot_items/{id}:
    get:
      summary: Get one loot_items record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Loot Items
