openapi: 3.2.0
info:
  title: GZW Data Items API
  version: 4.0.0
  description: Comprehensive Gray Zone Warfare game data API.
servers:
- url: https://gzw-data.dev
tags:
- name: Items
paths:
  /api/items:
    get:
      summary: items (3 items)
      tags:
      - Items
  /api/items/{id}:
    get:
      summary: Get one items record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Items
  /api/v1/items:
    get:
      summary: items (3 items)
      tags:
      - Items
  /api/v1/items/{id}:
    get:
      summary: Get one items record by id
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      tags:
      - Items
